Transform: AWS::Serverless-2016-10-31
Description: >
  https://github.com/kaihendry/sam-custom-domain
  Derived from
  https://github.com/awslabs/serverless-application-model/blob/develop/examples/2016-10-31/custom_domains_with_route53/template.yaml
Parameters:
  DomainName:
    Type: String
  ACMCertificateArn:
    Type: String
  HostedZoneId:
    Type: String
Resources:
  MyFunction:
    Type: AWS::Serverless::Function
    Properties:
      InlineCode: |
        exports.handler = async (event) => {
          const response = {
            statusCode: 200,
            body: JSON.stringify('Hello from kaihendry/sam-custom-domain!'),
          };
          return response;
        };
      Handler: index.handler
      Runtime: nodejs12.x
      Events:
        ProxyApiRoot:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Method: Get
            Path: /
        ProxyApiGreedy:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /{proxy+}
            Method: ANY

  MyApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Dev
      Domain:
        DomainName: !Ref DomainName
        CertificateArn: !Ref ACMCertificateArn
        EndpointConfiguration: EDGE
        Route53:
          HostedZoneId: !Ref HostedZoneId
