AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  https://github.com/kaihendry/sam-custom-domain

Parameters:
  DomainName:
    Type: String
  ACMCertificateArn:
    Type: String
  HostedZoneId:
    Type: String
Resources:
  MyFunction:
    Type: AWS::Serverless::Function
    Properties:
      InlineCode: |
          def handler(event, context):
              import json
              return {
                  "statusCode": 200,
                  "body": json.dumps(event),
              }
      Handler: index.handler
      Runtime: python3.7
      Events:
        ExplicitApi: # warning: creates a public endpoint
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Method: GET
            Path: /

  HttpApi:
    Type: AWS::Serverless::HttpApi

  ApiCustomDomain:
    Type: AWS::ApiGatewayV2::DomainName
    Properties:
      DomainName: !Ref DomainName
      DomainNameConfigurations:
        - CertificateArn: !Ref ACMCertificateArn
          EndpointType: REGIONAL

  ApiMapping:
    Type: AWS::ApiGatewayV2::ApiMapping
    Properties:
      DomainName: !Ref DomainName
      ApiId: !Ref HttpApi
      Stage: "$default"

  RegionalRoute53Record:
    Type: AWS::Route53::RecordSet
    Properties:
      SetIdentifier: http-testing
      AliasTarget:
        DNSName: !Ref DomainName
        HostedZoneId: !Ref HostedZoneId
      Name: !Ref DomainName
      HostedZoneId: !Ref HostedZoneId
      Region: ap-southeast-1
      Type: A
